# File: config/config.py

import argparse

def parse_args():
    parser = argparse.ArgumentParser(description='Train Audio Model with Learning Rate Scheduler')
    parser.add_argument('--batch_size', type=int, default=200, help='Batch size for training')
    parser.add_argument('--max_epoch', type=int, default=500, help='Maximum number of epochs')
    parser.add_argument('--learning_rate', type=float, default=1e-3, help='Initial learning rate')
    parser.add_argument('--seed', type=int, default=20, help='Random seed')
    parser.add_argument('--num_classes', type=int, default=4, help='Number of classes')
    parser.add_argument('--sample_rate', type=int, default=128000, help='Sample rate for audio')
    parser.add_argument('--window_size', type=int, default=2048, help='Window size for audio feature extraction')
    parser.add_argument('--hop_size', type=int, default=1024, help='Hop size for audio feature extraction')
    parser.add_argument('--mel_bins', type=int, default=64, help='Number of mel bins for audio feature extraction')
    parser.add_argument('--fmin', type=int, default=50, help='Minimum frequency for mel bins')
    parser.add_argument('--fmax', type=int, default=None, help='Maximum frequency for mel bins')
    parser.add_argument('--patience', type=int, default=500, help='Patience for learning rate scheduler')
    parser.add_argument('--factor', type=float, default=0.1, help='Factor by which the learning rate will be reduced')
    parser.add_argument('--data_path', type=str, default='/mnt/users/chadolor/work/Datasets/affia3k/', help='Path to the dataset')
    parser.add_argument('--dataset', type=str, default='affia3k', help='Dataset to use for training and validation')
    parser.add_argument('--loss', type=str, default='ce', help='Loss function to use (ce, focal, softboot, hardboot)')
    parser.add_argument('--model_name', type=str, default='cnn10', help='Name of the model to use')
    parser.add_argument('--audiomentations', action='store_true', help='Apply audiomentations')
    parser.add_argument('--label_smoothing', type=float, default=0.0, help='Label smoothing factor')
    parser.add_argument('--filter_chance', type=float, default=0.13, help='Chance of applying filter')
    parser.add_argument('--wandb_mode', type=str, default='offline', help='WandB mode (online/offline)')
    parser.add_argument('--wandb_project', type=str, default='affia3k', help='WandB project name')
    parser.add_argument('--lr_warmup', action='store_true', help='Apply learning rate warm-up')
    parser.add_argument('--warmup_epochs', type=int, default=5, help='Number of warm-up epochs')
    parser.add_argument('--freq_band', type=str, default='none', help='Frequency band for filtering (low, mid, high, none)')
    parser.add_argument('--frontend', type=str, default='logmel', help='Frontend type (logmel, mixup, diffres)')
    return parser.parse_args()
